#!/usr/bin/env python3
"""
Generate swaync style.css with Material You colors from the current awww wallpaper.
Usage: python generate-style.py [path/to/wallpaper]
  If no path given, auto-detects from `awww query`.
"""

import sys
import subprocess
from pathlib import Path

from PIL import Image
from materialyoucolor.scheme.scheme import Scheme
from materialyoucolor.palettes.core_palette import CorePalette


OUTPUT = Path(__file__).resolve().parent / "style.css"
SWAYNC_RELOAD = ["swaync-client", "--reload-css"]


def argb_to_hex(argb: int) -> str:
    """Convert ARGB int (0xAARRGGBB) to #RRGGBB hex string."""
    return f"#{((argb >> 16) & 0xFF):02X}{((argb >> 8) & 0xFF):02X}{(argb & 0xFF):02X}"


def get_wallpaper_path() -> str | None:
    """Get current wallpaper path from awww query."""
    try:
        out = subprocess.check_output(["awww", "query"], text=True, timeout=3)
        for line in out.strip().splitlines():
            if "currently displaying: image:" in line:
                return line.split("image:")[1].strip()
    except Exception:
        pass
    return None


def generate_colors(image_path: str) -> dict[str, str]:
    """
    Extract Material You dark scheme colors from an image.
    Returns a dict of hex color strings keyed by token name.
    """
    from materialyoucolor.quantize import QuantizeCelebi
    from materialyoucolor.score.score import Score

    # Load and resize image for fast processing
    img = Image.open(image_path).convert("RGBA")
    img.thumbnail((112, 112))

    # Get pixels as list of [r, g, b, a] — the format QuantizeCelebi expects
    pixels_rgba = [list(px) for px in img.getdata() if px[3] >= 128]

    if not pixels_rgba:
        raise ValueError("No non-transparent pixels found in image")

    # Quantize to find dominant colors, then score and pick the best source color
    quantized = QuantizeCelebi(pixels_rgba, 128)
    ranked = Score.score(quantized)
    source_argb = ranked[0]

    # Build dark scheme
    scheme = Scheme.dark(source_argb)

    # Also get the core palette for surfaceContainer tones
    core = CorePalette.of(source_argb)

    def tone(hex_val: int) -> str:
        return argb_to_hex(hex_val)

    return {
        # Directly from Scheme
        "surface": tone(scheme.surface),
        "onSurface": tone(scheme.on_surface),
        "surfaceVariant": tone(scheme.surface_variant),
        "onSurfaceVariant": tone(scheme.on_surface_variant),
        "outline": tone(scheme.outline),
        "outlineVariant": tone(scheme.outline_variant),
        "primary": tone(scheme.primary),
        "onPrimary": tone(scheme.on_primary),
        "primaryContainer": tone(scheme.primary_container),
        "onPrimaryContainer": tone(scheme.on_primary_container),
        "error": tone(scheme.error),
        "errorContainer": tone(scheme.error_container),
        "onErrorContainer": tone(scheme.on_error_container),
        # Approximated: surfaceContainer ≈ one step above surface
        "surfaceContainer": tone(core.n1.tone(12)),
        "surfaceContainerHigh": tone(core.n1.tone(17)),
        "surfaceContainerHighest": tone(core.n1.tone(22)),
    }


CSS_TEMPLATE = """\
/* ─── Auto-generated by generate-style.py ─── */
/* Source: {source} */

@define-color surface {surface};
@define-color surfaceContainer {surfaceContainer};
@define-color surfaceContainerHigh {surfaceContainerHigh};
@define-color surfaceContainerHighest {surfaceContainerHighest};
@define-color onSurface {onSurface};
@define-color onSurfaceVariant {onSurfaceVariant};
@define-color outline {outline};
@define-color outlineVariant {outlineVariant};
@define-color primary {primary};
@define-color onPrimary {onPrimary};
@define-color primaryContainer {primaryContainer};
@define-color onPrimaryContainer {onPrimaryContainer};
@define-color error {error};
@define-color errorContainer {errorContainer};
@define-color onErrorContainer {onErrorContainer};

* {{
  font-family: 'Adwaita Sans', 'Inter', 'Google Sans Text', sans-serif;
  transition: all 0.25s ease-in-out;
  transition-property: background, background-color, color, border-color, box-shadow;
  border: none;
  box-shadow: none;
  outline: none;
}}

notificationwindow, blankwindow {{
  background: transparent;
}}

.floating-notifications .notification {{
  background: transparent;
  margin-bottom: 8px;
}}

.notification-row {{
  background: transparent;
  outline: none;
  margin: 0 8px 8px 8px;
}}

.notification-row .notification-background .notification {{
  background-color: alpha(@surfaceContainerHigh, 0.92);
  border: 1px solid alpha(@outline, 0.15);
  border-radius: 16px;
  padding: 6px 0;
}}

.notification-row .notification-background .notification.critical {{
  background-color: alpha(@errorContainer, 0.95);
  border-color: alpha(@error, 0.3);
}}

.notification-row .notification-background .notification .notification-default-action {{
  padding: 4px 12px;
  margin: 0;
  background: transparent;
  border: none;
  color: @onSurface;
  border-radius: 14px;
}}

.notification-row .notification-background .notification .notification-default-action:hover {{
  background-color: alpha(@onSurface, 0.08);
}}

.notification-row .notification-background .notification .notification-default-action .notification-content {{
  background: transparent;
  border-radius: 14px;
  padding: 0;
}}

.notification-row .notification-background .notification .notification-default-action .notification-content .image {{
  -gtk-icon-size: 56px;
  border-radius: 12px;
  margin: 0 12px 0 2px;
}}

.notification-row .notification-background .notification .notification-default-action .notification-content .app-icon {{
  -gtk-icon-size: 24px;
  margin: 2px 8px 2px 0;
}}

.notification-row .notification-background .notification .notification-default-action .notification-content .text-box .summary {{
  font-size: 16px;
  font-weight: 500;
  color: @onSurface;
  margin-bottom: 2px;
}}

.notification-row .notification-background .notification .notification-default-action .notification-content .text-box .time {{
  font-size: 13px;
  font-weight: 400;
  color: @onSurfaceVariant;
  margin-right: 32px;
}}

.notification-row .notification-background .notification .notification-default-action .notification-content .text-box .body {{
  font-size: 14px;
  font-weight: 400;
  color: @onSurfaceVariant;
}}

/* Critical notification overrides */
.notification-row .notification-background .notification.critical .notification-default-action .notification-content .text-box .summary {{
  color: @onErrorContainer;
}}

.notification-row .notification-background .notification.critical .notification-default-action .notification-content .text-box .body {{
  color: @onErrorContainer;
}}

.notification-row .notification-background .notification.critical .notification-default-action .notification-content .text-box .time {{
  color: @onErrorContainer;
}}

/* ─── Close Button ─── */
.close-button {{
  background: alpha(@onSurface, 0.1);
  color: @onSurface;
  border-radius: 100%;
  min-width: 26px;
  min-height: 26px;
  margin: 6px 8px 0 0;
  padding: 0;
}}

.close-button:hover {{
  background: alpha(@onSurface, 0.2);
}}

/* ─── Action Buttons ─── */
.notification-action button {{
  border-radius: 12px;
  padding: 6px 14px;
  color: @primary;
  background: alpha(@primary, 0.08);
  margin: 4px;
  font-weight: 500;
  font-size: 13px;
}}

.notification-action button:hover {{
  background: alpha(@primary, 0.15);
}}

/* ─── Inline Reply ─── */
.notification-row .notification-background .notification .notification-default-action .notification-content .inline-reply {{
  margin-top: 6px;
}}

.notification-row .notification-background .notification .notification-default-action .notification-content .inline-reply .inline-reply-entry {{
  background: alpha(@surface, 0.6);
  color: @onSurface;
  caret-color: @onSurface;
  border: 1px solid alpha(@outline, 0.15);
  border-radius: 12px;
}}

.notification-row .notification-background .notification .notification-default-action .notification-content .inline-reply .inline-reply-button {{
  margin-left: 6px;
  background: alpha(@primary, 0.1);
  border: 1px solid alpha(@outline, 0.1);
  border-radius: 12px;
  color: @primary;
}}

.notification-row .notification-background .notification .notification-default-action .notification-content .inline-reply .inline-reply-button:hover {{
  background: alpha(@primary, 0.2);
}}

/* ─── Notification Body Image ─── */
.notification-row .notification-background .notification .notification-default-action .notification-content .body-image {{
  margin-top: 6px;
  background-color: transparent;
  border-radius: 10px;
}}

/* ─── Progress Bar ─── */
.notification-row .notification-background .notification .notification-default-action .notification-content progressbar {{
  margin-top: 4px;
}}

.notification-row .notification-background .notification .notification-default-action .notification-content progressbar trough {{
  background: alpha(@onSurface, 0.1);
  border-radius: 8px;
  min-height: 4px;
}}

.notification-row .notification-background .notification .notification-default-action .notification-content progressbar progress {{
  background: @primary;
  border-radius: 8px;
}}

/* ─── Control Center ─── */
.control-center {{
  background: alpha(@surfaceContainer, 0.92);
  border-radius: 20px;
  border: 1px solid alpha(@outline, 0.15);
  color: @onSurface;
}}

.control-center .control-center-list {{
  background: transparent;
}}

.control-center .control-center-list-placeholder {{
  opacity: 0.4;
  color: @onSurfaceVariant;
}}

/* ─── Control Center: Widget Title ─── */
.widget-title > label {{
  font-size: 1.3rem;
  font-weight: 500;
  color: @onSurface;
  margin-right: 8px;
}}

.widget-title > button {{
  border-radius: 12px;
  background: alpha(@onSurface, 0.08);
  color: @onSurface;
  padding: 4px 12px;
  font-size: 0.9rem;
}}

.widget-title > button:hover {{
  background: alpha(@onSurface, 0.15);
}}

/* ─── Control Center: DND Toggle ─── */
.widget-dnd label {{
  color: @onSurface;
  font-size: 1rem;
  margin-right: 8px;
}}

.widget-dnd switch {{
  background: @outlineVariant;
  border-radius: 16px;
  min-height: 16px;
  padding: 2px;
}}

.widget-dnd switch slider {{
  background: @outline;
  border-radius: 16px;
  min-width: 14px;
  min-height: 14px;
}}

.widget-dnd switch:checked {{
  background: @primary;
}}

.widget-dnd switch:checked slider {{
  background: @onPrimary;
}}

/* ─── Generic Widget Spacing ─── */
.control-center .widget {{
  margin: 6px 10px;
  padding: 10px 14px;
  border-radius: 14px;
  background: alpha(@surfaceContainerHigh, 0.5);
}}

.control-center .widget:first-child {{
  margin-top: 12px;
}}

/* ─── Notification Groups ─── */
.notification-group .notification-group-headers {{
  color: @onSurface;
  margin: 0 16px;
}}

.notification-group .notification-group-headers .notification-group-header {{
  color: @onSurface;
  font-weight: 500;
}}

.notification-group .notification-group-headers .notification-group-icon {{
  color: @onSurfaceVariant;
  -gtk-icon-size: 28px;
}}

.notification-group .notification-group-close-button .close-button {{
  margin: 10px 18px;
}}

/* ─── Blank Window (behind control center) ─── */
.blank-window {{
  background: transparent;
}}
"""


def main() -> None:
    # Determine wallpaper path
    wallpaper = sys.argv[1] if len(sys.argv) > 1 else get_wallpaper_path()
    if not wallpaper or not Path(wallpaper).exists():
        print(f"Error: no valid wallpaper found ({wallpaper or 'none'})")
        sys.exit(1)

    print(f"Generating colors from: {Path(wallpaper).name}")
    colors = generate_colors(wallpaper)

    # Write style.css
    css = CSS_TEMPLATE.format(source=Path(wallpaper).name, **colors)
    OUTPUT.write_text(css)
    print(f" wrote: {OUTPUT}")

    # Reload swaync
    try:
        subprocess.run(SWAYNC_RELOAD, check=False, timeout=5)
        print(" reloaded swaync")
    except Exception as e:
        print(f" warning: swaync reload failed ({e})")


if __name__ == "__main__":
    main()
