pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

// ColorSync — reads waybar/colors.css (generated by generate-style.py) and updates Theme
Singleton {
    id: root

    Process {
        id: colorProc
        running: false
        command: ["sh", "-c",
            "grep '@define-color' " + Quickshell.env("HOME") + "/.config/waybar/colors.css 2>/dev/null | awk '{print $2, $3}'"]
        stdout: SplitParser {
            onRead: data => {
                var parts = data.trim().split(" ")
                if (parts.length < 2) return
                var name = parts[0]; var hex = parts[1]
                switch (name) {
                    case "surface":              Theme.bg = hex; break
                    case "surfaceContainer":     Theme.bgRaised = hex; break
                    case "onSurface":            Theme.fg = hex; break
                    case "onSurfaceVariant":     Theme.fgDim = hex; break
                    case "primary":              Theme.accentGreen = hex; break
                    case "secondary":            Theme.accentGold = hex; break
                    case "tertiary":             Theme.accentBlue = hex; break
                }
            }
        }
    }

    // Check for new colors every 3s (wallpaper changes → generate-style.py runs → colors.css updated)
    Timer { interval: 3000; repeat: true; running: true
        onTriggered: colorProc.running = true }
}
